### ISSUE TITLE
The time step t is not used?

### ISSUE THREAD

**Issue by PanXiebit** [samb-t/unleashing-transformers#10]
https://github.com/samb-t/unleashing-transformers/blob/3e5f56456454d8dc22673a471dfadf98ca77f9e0/models/transformer.py?_pjax=%23js-repo-pjax-container#L130

The denoise_fn is Transformer, but in the forward of this model, the time step t is not used?

**Comment by samb-t** [comment]
Hi, yes that's correct. In our early experiments we tested the impact of conditioning the Transformer on time but didn't find it to have much of an effect.

My guess as to why this doesn't matter so much in the discrete absorbing diffusion case is that it's relatively simple for the model to figure out what the time step is based on the number of input tokens that are masks. Whereas in the continuous Gaussian case it's much less obvious how noisy the inputs are.

Hope this helps!

**Comment by PanXiebit** [comment]
@samb-t  Thanks a lot! This really helps.
