### ISSUE TITLE
Training log

### ISSUE THREAD

**Issue by XiSHEN0220** [samb-t/unleashing-transformers#13]
Dear authors, 

Thanks a lot for sharing the code, which is quite clean and easy to read !!

I plan to train the model from scratch.
As the training takes ~10 days (c.f. [issue 11](https://github.com/samb-t/unleashing-transformers/issues/11#issuecomment-1169840543)), I am wondering whether it is possible to share your training log corresponding to the experiments of Lsun churches ([VQGAN](https://github.com/samb-t/unleashing-transformers#train-a-vector-quantized-autoencoder-on-lsun-churches) and [Absorbing Diffusion sampler](https://github.com/samb-t/unleashing-transformers#train-an-absorbing-diffusion-sampler-using-the-above-vector-quantized-autoencoder)).

Finally, in the paper Sec.4.4, you mentioned that leveraging Diff Aug + $\lambda_{max} = 1$ leads to better performance. However, [in the provided config](https://github.com/samb-t/unleashing-transformers#train-a-vector-quantized-autoencoder-on-lsun-churches), if I understand correctly, [the diff aug is set to False](https://github.com/samb-t/unleashing-transformers#train-an-absorbing-diffusion-sampler-using-the-above-vector-quantized-autoencoder).

**Comment by XiSHEN0220** [comment]
Dear, authors, 

I have another question about the FID evaluation. 

If I understand correctly, the FID provided in the code is computed on the training set? (i.e. real and reconstructed images are both for the training set) 

The details can be found in the following scripts:  

* [calc_VQGAN_FID line 18](https://github.com/samb-t/unleashing-transformers/blob/master/experiments/calc_VQGAN_FID.py#L18)
* [vqgan_utils line 78](https://github.com/samb-t/unleashing-transformers/blob/master/utils/vqgan_utils.py#L78)
* [vqgan_utils line 93-111](https://github.com/samb-t/unleashing-transformers/blob/master/utils/vqgan_utils.py#L93-L111)
* [data_utils line 152-193](https://github.com/samb-t/unleashing-transformers/blob/master/utils/data_utils.py#L152-L193) 

If this is true, does it make sense to report FID on the training set? 

Thanks for your time !! 
Best,

**Comment by peterhessey** [comment]
Hi, thanks for your interest in our paper and code! I shall answer your questions in order:

> I am wondering whether it is possible to share your training log corresponding to the experiments of Lsun churches

* Unfortunately we can't share training logs currently as the contain references to sensitive university info that would need to be cleaned out first. If this would be of significant use to all users though we may be able to facilitate this in the future.

> However, [in the provided config](https://github.com/samb-t/unleashing-transformers#train-a-vector-quantized-autoencoder-on-lsun-churches), if I understand correctly, [the diff aug is set to False](https://github.com/samb-t/unleashing-transformers#train-an-absorbing-diffusion-sampler-using-the-above-vector-quantized-autoencoder).

* Good spot! That should not be set to False by default, please change it if you're trying to repeat experiments :)

> If this is true, does it make sense to report FID on the training set?

This is an interesting point. I think it does make sense, as we in some ways don't want the VQGAN to generalise. We want the VQGAN to learn a latent space and a codebook that stores as much information as possible using the available data. As such reporting FID on the test/validation sets isn't really of any relevance, as the diffusion-sampler won't be affect by that data, it only cares about the latent space of the training data that the VQGAN actually used! 

We would be keen to hear your thoughts on this though :)

**Comment by XiSHEN0220** [comment]
Thanks for your reply !!!
It really helps me a lot~~  
I close the issue.
