### ISSUE TITLE
Is this work not rely on other vqgan pretrained model?

### ISSUE THREAD

**Issue by YilanWang** [samb-t/unleashing-transformers#16]
I have only done cv tasks similar to classification before, but they are all rely on a big pretrained model, like imagenet-1k dataset. But I don't find this in unleashing tranformer. So is it really not needed? Many thanks~

**Comment by samb-t** [comment]
Sorry for the delay. That's right, no pretrained VQGANs are needed. We train each VQGAN separately for each dataset as we want the best reconstruction quality we can get for that dataset (and the datasets are big enough for this). This approach is standard when benchmarking generative models on these datasets. Whereas, if you have a very small dataset then you may want to train a VQGAN on a larger dataset that is sufficiently similar to your small dataset such as ImageNet or LAION-5B and fine-tune. Hope this helps, if you have any other questions feel free to ask!

**Comment by YilanWang** [comment]
many thx for your reply! I close this repo.
