### ISSUE TITLE
What does Table 1 (t=1 and t=0.9) refer to in the paper? It doesn't seem to be mentioned in the text.

### ISSUE THREAD

**Issue by Yanghaotian-CV** [samb-t/unleashing-transformers#22]
(t=1 and t=0.9) ,Which hyperparameter do these two experimental configurations refer to?

**Comment by peterhessey** [comment]
This is referring to the temperature parameter :)

**Comment by Yanghaotian-CV** [comment]
> This is referring to the temperature parameter :)

Tanks, i can see the description(temperature), but i don't know what it means. I didn't find this hyperparameter in the code.

**Comment by peterhessey** [comment]
You'll see this defined under `H.temp` for the hyperparmeter objects a lot of the time! For example here:

https://github.com/samb-t/unleashing-transformers/blob/master/hparams/defaults/sampler_defaults.py#L15

Searching for ".temp" in the codebase should show all the places temperature is used.

**Comment by Yanghaotian-CV** [comment]
Thank you very much! Finally, I'd like to ask you, is there any research after this work?

**Comment by peterhessey** [comment]
Not from myself, but you can see some of Sam's great work [here](https://scholar.google.com/citations?user=xQ4rXyoAAAAJ&hl=en&oi=ao) and citations for the Unleashing Transformers paper [here](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=7593120029891493996&as_sdt=5) that should give you some ideas for other research to explore 😀

**Comment by Yanghaotian-CV** [comment]
Thanks. That's really helpful！&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peter ***@***.***&gt;; 
发送时间: 2024年12月20日(星期五) 下午5:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [samb-t/unleashing-transformers] What does Table 1 (t=1 and t=0.9) refer to in the paper? It doesn&#39;t seem to be mentioned in the text. (Issue #22)





 
Not from myself, but you can see some of Sam's great work here and citations for the Unleashing Transformers paper here that should give you some ideas for other research to explore 😀
 
&mdash;
