### ISSUE TITLE
link to paper is broken

### ISSUE THREAD

**Issue by kendrick90** [samb-t/unleashing-transformers#7]
Found here: https://arxiv.org/abs/2111.12701

Also curious how long training took? You mentioned one 2080 but was that 1 week? 2 months?

**Comment by samb-t** [comment]
Thanks, the paper links have been updated now. As for training time, the combined time for both models was 10 days.

**Comment by kendrick90** [comment]
Thanks I'm thinking to try training it on imagenet.
