### ISSUE TITLE
Pre-trained Checkpoints?

### ISSUE THREAD

**Issue by gnobitab** [samb-t/unleashing-transformers#8]
Hi authors!

Thanks for open-sourcing this excellent work! Could I know whether you are planning to release your pre-trained checkpoints? 

Thanks in advance!

**Comment by samb-t** [comment]
Hi, sorry for the delay, I’ve been taking a break over Christmas/New Year. We have just been doing some final checks before releasing the checkpoints. Happy now to share them in [this](https://drive.google.com/drive/folders/1pjTYcm-2NNzuAiNEO24gSt9dXu_kGQ6b?usp=sharing) Google Drive folder. To download all models, download the logs folder to the root of this repo. Let me know if you have any problems accessing them.
